### ISSUE TITLE
Crashlog on dedicated server

### ISSUE THREAD

**Issue by Kehaan** [aziascreations/Minecraft-Vending-Machine-Revamped#1]
Crash when trying to use a vending machine and iron coins on a dedicated server. 

Crashlog:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/10/15 8:04 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.func_70016_h(DDD)V
    at com.azias.vendingmachine.blocks.BlockVendingMachine.func_149727_a(BlockVendingMachine.java:161)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4171742952 bytes (3978 MB) / 5028577280 bytes (4795 MB) up to 21963079680 bytes (20945 MB)
    JVM Flags: 17 total; -Xms5048m -Xmx22048m -XX:PermSize=512m -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 26 mods loaded, 26 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.44} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJAAAA   RenderPlayerAPI{1.4} [Render Player API](minecraft.jar) 
    UCHIJAAAA   antiqueatlas{4.2.7-1.7.10} [Antique Atlas](antiqueatlas-4.2.7-1.7.10.jar) 
    UCHIJAAAA   AntMan{Beta-1.7.10-1.3.1} [AntMan](AntMan-Beta-1.7.10-1.3.1.jar) 
    UCHIJAAAA   BiblioCraft{1.10.4} [BiblioCraft](BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   chisel{2.4.1.40} [Chisel 2](Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   ctmlib{1.0.1.5} [CTMLib](Chisel2-2.4.1.40.jar) 
    UCHIJAAAA   chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCHIJAAAA   customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) 
    UCHIJAAAA   props{2.0.2} [Decocraft](Decocraft-2.0.2_1.7.10.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.10} [Extra Utilities](extrautilities-1.2.10.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJAAAA   Mystcraft{0.12.3.00} [Mystcraft](mystcraft-1.7.10-0.12.3.00.jar) 
    UCHIJAAAA   punt{1.7.10-10.13.0-16.1} [Punt](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   whitehall{1.7.10-10.13.0-16.1} [Whitehall](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   hoy{1.7.10-10.13.0-16.1} [Hoy](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   smallboats{1.7.10-10.13.0-16.1} [SmallBoats (base)](smallboats-1.7.10-10.13.0-16.1.jar) 
    UCHIJAAAA   aziasvendingmachine{1.0.1} [Vending Machines Revamped](VendingMachinesRevamped_1.0.1_1.7.10.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 20; [EntityPlayerMP['V12volante'/325, l='world', x=-60.27, y=99.00, z=270.73]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by ghost** [comment]
@AziasYur `func_70016_h` (aka `setVelocity`) is a client-side method.

**Comment by Kehaan** [comment]
The crash is just by using the vending machine on  a server.

**Comment by ghost** [comment]
Yeah, @AziasYur has to change the code to be compatible with dedicated servers.

**Comment by aziascreations** [comment]
I will fix that when I get back home (~8 days).
I'm so sorry.

**Comment by Kehaan** [comment]
No worries. Was going to use it for a episode of some adventure maps i make for MrCrainer (Youtuber). But then had some server crashes when testing the map. I will use it for another episode then, when the bug is fixed :)

**Comment by aziascreations** [comment]
It's fixed :)

**Comment by Kehaan** [comment]
Thank you <3
